Resources:
  BanListTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: false
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      TableName: ${self:service}-ban-list-table
  DealerListTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: false
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      TableName: ${self:service}-dealer-list-table


Outputs:
  BanListTable:
    Value: !Ref BanListTable
  BanListTableArn:
    Value: !GetAtt BanListTable.Arn
  BanListTableStreamArn:
    Value: !GetAtt BanListTable.StreamArn
  DealerListTable:
    Value: !Ref DealerListTable
  DealerListTableArn:
    Value: !GetAtt DealerListTable.Arn
  DealerListTableStreamArn:
    Value: !GetAtt DealerListTable.StreamArn
