service: dealer-api
app: tsa
org: jordmax12
frameworkVersion: '^3'
configValidationMode: error

provider:
  name: aws
  region: us-east-1
  runtime: nodejs18.x
  architecture: arm64
  memorySize: 512
  apiGateway:
    apiKeys:
      - value: ${ssm:/TSA_DEALER_API_KEY}
        description: API key for TSA auto ban API.
    disableDefaultEndpoint: false
  environment:
    STAGE: ${sls:stage}
    REGION: ${aws:region}
    DEALER_LIST_TABLE: ${cf:database-${sls:stage}.DealerListTable}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - cloudwatch:*
          Resource:
            - '*'
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource:
            - '${cf:database-${sls:stage}.DealerListTableArn}'
            - '${cf:database-${sls:stage}.DealerListTableArn}/index/*'

functions:
  addToDealerList:
    handler: add-to-dealer-list.handler
    name: tsa-add-to-dealer-list
    timeout: 30
    events:
      - http:
          method: POST
          path: add
          private: true
          cors: true

plugins:
  - serverless-plugin-monorepo
