service: auto-ban-api
app: tsa
org: jordmax12
frameworkVersion: '^3'
configValidationMode: error

provider:
  name: aws
  region: us-east-1
  runtime: nodejs18.x
  architecture: arm64
  memorySize: 512
  apiGateway:
    apiKeys:
      - value: ${ssm:/TSA_ADD_BAN_LIST_API_KEY}
        description: API key for TSA auto ban API.
    disableDefaultEndpoint: false
  environment:
    STAGE: ${sls:stage}
    REGION: ${aws:region}
    BAN_LIST_TABLE: ${cf:database-${sls:stage}.BanListTable}
    LEGACY_API_ENDPOINT: ${ssm:/LEGACY_API_ENDPOINT}
    LEGACY_API_KEY: ${ssm:/LEGACY_API_KEY}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - cloudwatch:*
          Resource:
            - '*'
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource:
            - '${cf:database-${sls:stage}.BanListTableArn}'
            - '${cf:database-${sls:stage}.BanListTableArn}/index/*'

functions:
  addToBanList:
    handler: add-to-ban-list.handler
    name: tsa-add-to-ban-list
    timeout: 30
    events:
      - http:
          method: POST
          path: add
          private: true
          cors: true

plugins:
  - serverless-plugin-monorepo
