Resources:
  BanListTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: false
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      TableName: ${self:service}-ban-list-table
  DealerListTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: false
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      TableName: ${self:service}-dealer-list-table
